version: '3.3'

services:
  baby-front:
    build: ./front
    restart: always
    ports:
      - '8080:80'
    links:
      - baby-back
  baby-back:
    build: ./back
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./back/.env
    links:
      - baby-db
  baby-db:
    build: ./database
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    volumes:
      - babyfootdata:/var/lib/postgresql/data

volumes:
  babyfootdata:
